const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

async function initializeDatabase() {
    let connection;
    try {
        // 1. 설정 로드
        const configPath = path.resolve(__dirname, '../../config.yaml');
        const config = yaml.load(fs.readFileSync(configPath, 'utf8'));
        const dbConfig = config.database;
        const walletAbsPath = path.resolve(dbConfig.walletPath);

        // 2. [전체 디버깅 로그] 비밀번호 포함 출력
        console.log("=========================================");
        console.log("[DB 전체 디버그] 접속 설정 상세 내역");
        console.log(` > USER     : ${dbConfig.user}`);
        console.log(` > PASSWORD : ${dbConfig.password}`); // 비밀번호 확인용
        console.log(` > TNS_NAME : ${dbConfig.connectString}`);
        console.log(` > WALLET   : ${walletAbsPath}`);
        console.log("=========================================");

        // 3. Oracle Connection 시도
        connection = await oracledb.getConnection({
            user: dbConfig.user,
            password: dbConfig.password,
            connectString: dbConfig.connectString,
            configDir: walletAbsPath,
            walletLocation: walletAbsPath,
            walletPassword: "", 
            connectTimeout: 15
        });

        console.log("[DB] Oracle Database 연결 성공!");

        // 4. 테이블 초기화 로직 (기존 유지)
        const queries = [
            `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE KAKAOWEB_SESSIONS (SESSION_ID VARCHAR2(100) PRIMARY KEY, AUTH_TOKEN VARCHAR2(500), DEVICE_UUID VARCHAR2(100), LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
            `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE KAKAOWEB_CHAT_LOGS (LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, SESSION_ID VARCHAR2(100), SENDER_NAME VARCHAR2(100), MESSAGE CLOB, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`
        ];

        for (const sql of queries) {
            await connection.execute(sql);
        }

        console.log("[DB] 테이블 무결성 검사 및 초기화 완료.");
        return connection;

    } catch (err) {
        console.error("\n[DB 접속 및 초기화 에러]");
        console.error(` > 에러 내용: ${err.message}`);
        throw err;
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) {}
        }
    }
}

module.exports = initializeDatabase;
