const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

async function initializeDatabase() {
    let connection;
    try {
        const configPath = path.resolve(__dirname, '../../config.yaml');
        const config = yaml.load(fs.readFileSync(configPath, 'utf8'));
        const dbConfig = config.database;

        // 1. 절대 경로 확정 (중요: 상대 경로를 쓰면 서비스 실행 시 경로가 꼬일 수 있음)
        const walletAbsPath = path.resolve(dbConfig.walletPath);

        console.log(`[DB] Wallet 경로 확인: ${walletAbsPath}`);
        
        // 2. Wallet 필수 파일 존재 여부 미리 체크
        if (!fs.existsSync(path.join(walletAbsPath, 'cwallet.sso'))) {
            throw new Error(`Wallet 파일(cwallet.sso)이 ${walletAbsPath}에 없습니다.`);
        }

        // 3. Oracle Connection (타임아웃 설정 추가)
        connection = await oracledb.getConnection({
            user: dbConfig.user,
            password: dbConfig.password,
            connectString: dbConfig.connectString,
            configDir: walletAbsPath,
            walletLocation: walletAbsPath,
            walletPassword: "", 
            connectTimeout: 10 // 10초 내에 연결 안 되면 에러 발생시키기
        });

        console.log(`[DB] Oracle ADB 연결 성공! (ConnectString: ${dbConfig.connectString})`);

        // 4. 스키마 초기화 (기존 쿼리 로직 유지)
        const queries = [
            `BEGIN 
                EXECUTE IMMEDIATE 'CREATE TABLE KAKAOWEB_SESSIONS (
                    SESSION_ID VARCHAR2(100) PRIMARY KEY, 
                    USER_ID VARCHAR2(100),
                    AUTH_TOKEN VARCHAR2(500), 
                    DEVICE_UUID VARCHAR2(100), 
                    REVISION NUMBER DEFAULT 0,
                    LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    IS_VALID CHAR(1) DEFAULT ''Y''
                )'; 
             EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
            `BEGIN 
                EXECUTE IMMEDIATE 'CREATE TABLE KAKAOWEB_CHAT_LOGS (
                    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    CHAT_ID NUMBER,
                    SENDER_ID NUMBER, 
                    MESSAGE CLOB, 
                    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )'; 
             EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`
        ];

        for (let sql of queries) {
            await connection.execute(sql);
        }
        await connection.commit();
        console.log("[DB] 스키마 초기화 완료.");
        
        return connection;

    } catch (err) {
        console.error("[DB] 치명적 오류 발생:");
        console.error(` > 메시지: ${err.message}`);
        throw err;
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) {}
        }
    }
}

module.exports = initializeDatabase;
