const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

async function initializeDatabase() {
    let connection;
    try {
        const configPath = path.resolve(__dirname, '../../config.yaml');
        const config = yaml.load(fs.readFileSync(configPath, 'utf8'));
        const dbConfig = config.database;
        const walletAbsPath = path.resolve(dbConfig.walletPath);

        console.log("=========================================");
        console.log("[DB 실행] 최종 연결 시도");
        console.log(` > WALLET PATH: ${walletAbsPath}`);
        console.log("=========================================");

        connection = await oracledb.getConnection({
            user: dbConfig.user,
            password: dbConfig.password,
            connectString: dbConfig.connectString,
            // Thin 모드 필수 설정
            configDir: walletAbsPath,
            walletLocation: walletAbsPath,
            walletPassword: "" // 빈 문자열을 명시적으로 전달
        });

        console.log(" 🎉 [DB] Oracle Database 연결 대성공!");

        // 테이블 생성 로직
        const queries = [
            `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE KAKAOWEB_SESSIONS (SESSION_ID VARCHAR2(100) PRIMARY KEY, AUTH_TOKEN VARCHAR2(500), DEVICE_UUID VARCHAR2(100), LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
            `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE KAKAOWEB_CHAT_LOGS (LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, SESSION_ID VARCHAR2(100), SENDER_NAME VARCHAR2(100), MESSAGE CLOB, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`
        ];

        for (const sql of queries) { await connection.execute(sql); }
        
        return connection;

    } catch (err) {
        console.error("\n❌ [DB 에러 발생]");
        console.error(`메시지: ${err.message}`);
        // 현재 Node 옵션 상태 확인 로그 추가
        console.log(`현재 NODE_OPTIONS: ${process.env.NODE_OPTIONS || '없음'}`);
        throw err;
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) {}
        }
    }
}

module.exports = initializeDatabase;
